-- Created-at...: September 24, 2023
-- Description..: This file was autogenerated
vim.g["duplicate-nvim-config"] = vim.g["duplicate-nvim-config"] or {
	visual = {
		selectAfter = true, -- do not select duplicated text
		block       = true  -- disable block-wise duplication
	}
}
return vim.g["duplicate-nvim-config"]
